import { lazy } from 'react'

// 게임을 추가하려면 이 배열에 항목을 하나 넣으면 됩니다.
// - id: 식별용 고유값
// - title, description, emoji: 허브 카드에 표시
// - category: 허브에서 그룹핑에 사용
// - component: React.lazy 로 감싼 게임 컴포넌트 → 선택 시에만 청크 로드(코드 스플리팅)
export const games = [
  {
    id: 'number-guess',
    title: '숫자 맞추기',
    description: '1부터 100까지의 숫자를 추측',
    emoji: '🔢',
    category: '퍼즐',
    component: lazy(() => import('./NumberGuess.jsx')),
  },
  {
    id: 'tic-tac-toe',
    title: '틱택토',
    description: '두 명이 번갈아 두는 삼목',
    emoji: '⭕',
    category: '보드',
    component: lazy(() => import('./TicTacToe.jsx')),
  },
  {
    id: 'memory',
    title: '카드 매칭',
    description: '같은 그림 카드 짝 맞추기',
    emoji: '🃏',
    category: '퍼즐',
    component: lazy(() => import('./Memory.jsx')),
  },
  {
    id: 'reaction',
    title: '반응속도 테스트',
    description: '초록불이 되면 최대한 빨리 클릭',
    emoji: '⚡',
    category: '테스트',
    component: lazy(() => import('./ReactionTime.jsx')),
  },
  {
    id: 'typing',
    title: '타이핑 속도',
    description: '문장을 빠르고 정확하게 입력',
    emoji: '⌨️',
    category: '테스트',
    component: lazy(() => import('./TypingTest.jsx')),
  },
  {
    id: 'quiz',
    title: '상식 퀴즈',
    description: '객관식 문제를 풀어보세요',
    emoji: '❓',
    category: '퀴즈',
    component: lazy(() => import('./Quiz.jsx')),
  },
  {
    id: 'clicker',
    title: '클리커',
    description: '클릭해서 포인트를 모으는 방치형',
    emoji: '🍪',
    category: '방치형',
    component: lazy(() => import('./Clicker.jsx')),
  },
  {
    id: '2048',
    title: '2048',
    description: '방향키로 같은 숫자를 합치기',
    emoji: '🔢',
    category: '퍼즐',
    component: lazy(() => import('./Game2048.jsx')),
  },
  {
    id: 'snake',
    title: '스네이크',
    description: '먹이를 먹고 몸을 늘리는 뱀',
    emoji: '🐍',
    category: '아케이드',
    component: lazy(() => import('./Snake.jsx')),
  },
  {
    id: 'minesweeper',
    title: '지뢰찾기',
    description: '지뢰를 피해 칸을 여세요',
    emoji: '💣',
    category: '퍼즐',
    component: lazy(() => import('./Minesweeper.jsx')),
  },
  {
    id: 'sliding-puzzle',
    title: '슬라이딩 퍼즐',
    description: '숫자를 순서대로 맞추는 15퍼즐',
    emoji: '🧩',
    category: '퍼즐',
    component: lazy(() => import('./SlidingPuzzle.jsx')),
  },
  {
    id: 'gomoku',
    title: '오목',
    description: '먼저 다섯 개를 잇는 사람이 승리',
    emoji: '⚫',
    category: '보드',
    component: lazy(() => import('./Gomoku.jsx')),
  },
  {
    id: 'blackjack',
    title: '블랙잭',
    description: '21에 가깝게! 딜러와 대결',
    emoji: '🃏',
    category: '카드',
    component: lazy(() => import('./Blackjack.jsx')),
  },
  {
    id: 'yahtzee',
    title: '야추',
    description: '주사위 5개로 족보 만들기',
    emoji: '🎲',
    category: '카드',
    component: lazy(() => import('./Yahtzee.jsx')),
  },
  {
    id: 'text-adventure',
    title: '텍스트 어드벤처',
    description: '선택에 따라 달라지는 이야기',
    emoji: '📖',
    category: '텍스트',
    component: lazy(() => import('./TextAdventure.jsx')),
  },
  {
    id: 'breakout',
    title: '벽돌깨기',
    description: '공을 튕겨 벽돌을 모두 깨기',
    emoji: '🧱',
    category: '아케이드',
    component: lazy(() => import('./Breakout.jsx')),
  },
  {
    id: 'pong',
    title: '퐁',
    description: 'AI와 벌이는 탁구 대결',
    emoji: '🏓',
    category: '아케이드',
    component: lazy(() => import('./Pong.jsx')),
  },
  {
    id: 'flappy',
    title: '플래피버드',
    description: '파이프 사이를 날아서 통과',
    emoji: '🐤',
    category: '아케이드',
    component: lazy(() => import('./FlappyBird.jsx')),
  },
  {
    id: 'tetris',
    title: '테트리스',
    description: '블록을 쌓아 줄을 없애기',
    emoji: '🟦',
    category: '아케이드',
    component: lazy(() => import('./Tetris.jsx')),
  },
  {
    id: 'shooter',
    title: '스크롤 슈터',
    description: '우주선으로 적을 격추',
    emoji: '🚀',
    category: '아케이드',
    component: lazy(() => import('./ScrollShooter.jsx')),
  },
  {
    id: 'pacman',
    title: '팩맨',
    description: '유령을 피해 도트를 모두 먹기',
    emoji: '👻',
    category: '아케이드',
    component: lazy(() => import('./PacMan.jsx')),
  },
  {
    id: 'othello',
    title: '오셀로',
    description: 'AI와 겨루는 리버시',
    emoji: '⚫',
    category: '보드',
    component: lazy(() => import('./Othello.jsx')),
  },
  {
    id: 'sudoku',
    title: '스도쿠',
    description: '9x9 숫자 논리 퍼즐',
    emoji: '🔢',
    category: '퍼즐',
    component: lazy(() => import('./Sudoku.jsx')),
  },
  {
    id: 'chess',
    title: '체스',
    description: 'AI와 겨루는 정통 체스',
    emoji: '♟️',
    category: '보드',
    component: lazy(() => import('./Chess.jsx')),
  },
  {
    id: 'checkers',
    title: '체커',
    description: '강제 캡처와 킹이 있는 체커',
    emoji: '🔴',
    category: '보드',
    component: lazy(() => import('./Checkers.jsx')),
  },
  {
    id: 'pool',
    title: '당구',
    description: '큐볼을 쳐서 공을 포켓에',
    emoji: '🎱',
    category: '물리',
    component: lazy(() => import('./PoolGame.jsx')),
  },
  {
    id: 'bowling',
    title: '볼링',
    description: '공을 굴려 핀을 쓰러뜨리기',
    emoji: '🎳',
    category: '물리',
    component: lazy(() => import('./Bowling.jsx')),
  },
  {
    id: 'slingshot',
    title: '새총',
    description: '발사체로 목표물을 맞히기',
    emoji: '🐦',
    category: '물리',
    component: lazy(() => import('./Slingshot.jsx')),
  },
  {
    id: 'car-race',
    title: '레이싱',
    description: '체크포인트 타임 트라이얼',
    emoji: '🏎️',
    category: '물리',
    component: lazy(() => import('./CarRace.jsx')),
  },
  {
    id: 'online-ttt',
    title: '온라인 틱택토',
    description: '방 코드로 실시간 대결',
    emoji: '🌐',
    category: '온라인',
    component: lazy(() => import('./OnlineTicTacToe.jsx')),
  },
  {
    id: 'online-gomoku',
    title: '온라인 오목',
    description: '방 코드로 실시간 오목 대결',
    emoji: '⚫',
    category: '온라인',
    component: lazy(() => import('./OnlineGomoku.jsx')),
  },
  {
    id: 'maze-3d',
    title: '3D 미로',
    description: '1인칭으로 미로를 탈출',
    emoji: '🧭',
    category: '3D',
    component: lazy(() => import('./Maze3D.jsx')),
  },
  {
    id: 'fps-3d',
    title: '3D 사격',
    description: '제한시간 안에 표적 맞히기',
    emoji: '🎯',
    category: '3D',
    component: lazy(() => import('./FPS3D.jsx')),
  },
  {
    id: 'race-3d',
    title: '3D 레이싱',
    description: '체크포인트 통과 타임 트라이얼',
    emoji: '🏎️',
    category: '3D',
    component: lazy(() => import('./Race3D.jsx')),
  },
]

export function getGame(id) {
  return games.find((game) => game.id === id)
}

// 등록된 게임에 등장하는 카테고리 목록(중복 제거, 등록 순서 유지)
export const categories = [...new Set(games.map((g) => g.category))]
