spring.application.name=music

server.port=8080

# DB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=music_project
spring.datasource.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=Qm9yblRvQmVQcm9kdWN0aW9uU2VjdXJlS2V5MTIzNDU2Nzg5

# 파일 업로드 최대 크기
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB

spring.web.resources.static-locations=file:C:/music_storage/