-- ① 기존 테이블 삭제 (재생성 시)
-- 외래키 참조 순서상 CONTACTS → CONTACT_GROUPS → USERS 순으로 삭제
DROP TABLE CONTACTS CASCADE CONSTRAINTS;
DROP TABLE CONTACT_GROUPS CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

-- ② 사용자 테이블
CREATE TABLE USERS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME    VARCHAR2(50)  NOT NULL UNIQUE,
    PASSWORD    VARCHAR2(255) NOT NULL,
    ROLE        VARCHAR2(20)  DEFAULT 'ROLE_USER',
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- ③ 그룹 테이블 (사용자별 소유)
CREATE TABLE CONTACT_GROUPS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID     NUMBER        NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    NAME        VARCHAR2(50)  NOT NULL,
    COLOR       VARCHAR2(7)   DEFAULT '#6366f1',
    CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
    -- 같은 사용자 안에서만 그룹 이름이 유일
    CONSTRAINT UQ_GROUPS_USER_NAME UNIQUE (USER_ID, NAME)
);

-- ④ 연락처 테이블 (사용자별 소유)
CREATE TABLE CONTACTS (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID         NUMBER        NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    NAME            VARCHAR2(100) NOT NULL,
    PHONE           VARCHAR2(20)  NOT NULL,
    EMAIL           VARCHAR2(100),
    POSTCODE        VARCHAR2(10),
    ADDR_ROAD       VARCHAR2(200),
    ADDR_JIBUN      VARCHAR2(200),
    ADDR_DETAIL     VARCHAR2(100),
    ADDR_EXTRA      VARCHAR2(100),
    GROUP_ID        NUMBER REFERENCES CONTACT_GROUPS(ID) ON DELETE SET NULL,
    IS_FAVORITE     NUMBER(1)     DEFAULT 0 CHECK (IS_FAVORITE IN (0, 1)),
    MEMO            VARCHAR2(500),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- ⑤ 인덱스
CREATE INDEX IDX_CONTACTS_USER     ON CONTACTS(USER_ID);
CREATE INDEX IDX_CONTACTS_NAME     ON CONTACTS(NAME);
CREATE INDEX IDX_CONTACTS_PHONE    ON CONTACTS(PHONE);
CREATE INDEX IDX_CONTACTS_GROUP    ON CONTACTS(GROUP_ID);
CREATE INDEX IDX_CONTACTS_FAVORITE ON CONTACTS(IS_FAVORITE);
CREATE INDEX IDX_CONTACTS_POSTCODE ON CONTACTS(POSTCODE);

COMMIT;
