CREATE USER talent_db IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO talent_db;
ALTER USER talent_db 
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

ALTER USER talent_db QUOTA UNLIMITED ON USERS;