spring.application.name=telephonebook

server.port=8080

spring.output.ansi.enabled=always

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=phonebook
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=여기에_사용할_매우_긴_랜덤_문자열을_입력하세요_최소_32자_이상
jwt.expiration=86400000

