CREATE TABLE ingredients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR) NOT NULL UNIQUE
);

CREATE TABLE recipes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(150 CHAR) NOT NULL,
    description VARCHAR2(1000 CHAR),
    cook_minutes NUMBER(4) NOT NULL
);

CREATE TABLE recipe_ingredients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id NUMBER NOT NULL,
    ingredient_id NUMBER NOT NULL,
    amount VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT fk_recipe_ingredients_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipes(id),
    CONSTRAINT fk_recipe_ingredients_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredients(id),
    CONSTRAINT uq_recipe_ingredient
        UNIQUE (recipe_id, ingredient_id)
);

CREATE TABLE user_ingredients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(50 CHAR) NOT NULL,
    ingredient_id NUMBER NOT NULL,
    CONSTRAINT fk_user_ingredients_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredients(id),
    CONSTRAINT uq_user_ingredient
        UNIQUE (user_id, ingredient_id)
);

CREATE INDEX idx_user_ingredients_user_id ON user_ingredients(user_id);
CREATE INDEX idx_recipe_ingredients_recipe_id ON recipe_ingredients(recipe_id);