CREATE USER music_project IDENTIFIED BY 1234
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO music_project;
GRANT CREATE SESSION TO music_project;
GRANT CREATE SEQUENCE TO music_project;
GRANT CREATE TRIGGER TO music_project;